require('config.keymaps')
require('config.autocmds')
require('config.plugin_keymaps')
require('lazyvim.config')
require('plugins.statusline')
require('plugins.colorscheme')
require('plugins.file_explorer')
require('plugins.tab')
require('plugins.mini')
require('plugins.noice')
require('plugins.toggleterm')
require('plugins.indent')
vim.o.laststatus = 0
